# Generated by Django 6.0.3 on 2026-04-07 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('mileage', models.FloatField()),
                ('seating', models.IntegerField()),
                ('car_type', models.CharField(max_length=50)),
                ('image', models.URLField()),
            ],
        ),
    ]
