# Generated by Django 6.0.3 on 2026-04-07 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0003_remove_userprofile_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='name',
            field=models.CharField(default='unknown', max_length=100),
            preserve_default=False,
        ),
    ]
